version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:3.9-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretcookie
      - RABBITMQ_NODENAME=rabbit@rabbitmq1
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq_net

  rabbitmq2:
    image: rabbitmq:3.9-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretcookie
      - RABBITMQ_NODENAME=rabbit@rabbitmq2
    ports:
      - "15682:15672"
      - "5673:5672"
    networks:
      - rabbitmq_net

  rabbitmq3:
    image: rabbitmq:3.9-management
    hostname: rabbitmq3
    container_name: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretcookie
      - RABBITMQ_NODENAME=rabbit@rabbitmq3
    ports:
      - "15692:15672"
      - "5674:5672"
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
