spring:
  application:
    name: rabbitmq-project
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672,localhost:5673,localhost:5674
rabbitmq:
  exchange: ex.project
  routing-key: routing_key
  message-rate: 10  # Messages per second

